# Generated by Django 3.2.3 on 2021-07-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210706_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Customer_Address',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
